# Generated by Django 5.2.10 on 2026-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("filters_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "saved_filters",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "query_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("filters_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_query_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HousingSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(db_index=True, max_length=200)),
                ("unit_type", models.CharField(db_index=True, max_length=64)),
                ("amenities_json", models.JSONField(blank=True, default=list)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housing_search_index",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["price"], name="housing_sea_price_1c4939_idx"),
                    models.Index(
                        fields=["location", "unit_type"],
                        name="housing_sea_locatio_3fa561_idx",
                    ),
                    models.Index(
                        fields=["is_available", "updated_at"],
                        name="housing_sea_is_avai_c6e16b_idx",
                    ),
                ],
            },
        ),
    ]
