# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="payer_account_number",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="payer_bank_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
