# Generated by Django 5.2.10 on 2026-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HousingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True, unique=True)),
                (
                    "min_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("preferred_types", models.JSONField(blank=True, default=list)),
                ("preferred_services", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housing_preferences",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="LifestylePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("quietness_score", models.PositiveSmallIntegerField(default=3)),
                ("cleanliness_score", models.PositiveSmallIntegerField(default=3)),
                ("sleep_schedule_score", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lifestyle_preferences",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profile_media",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("first_name", models.CharField(blank=True, default="", max_length=64)),
                ("last_name", models.CharField(blank=True, default="", max_length=64)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "university",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["user_id"],
            },
        ),
    ]
