# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="governorate",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
