# Generated by Django 5.2.10 on 2026-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GatewayRateLimitPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("ip", "IP Address"), ("user", "User Identifier")],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("limit_per_minute", models.PositiveIntegerField()),
                ("burst_limit", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gateway_rate_limit_policies",
                "ordering": ["scope"],
            },
        ),
        migrations.CreateModel(
            name="GatewayRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                ("method", models.CharField(max_length=16)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_identifier",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gateway_request_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewayRouteRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_prefix", models.CharField(max_length=64, unique=True)),
                ("upstream_base_url", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gateway_route_registry",
                "ordering": ["route_prefix"],
            },
        ),
    ]
