# Generated by Codex on 2026-04-10

from django.db import migrations


DEFAULT_ROUTES = {
    "auth": "http://localhost:8001/auth",
    "users": "http://localhost:8002/users",
    "housing": "http://localhost:8003/housing",
    "search": "http://localhost:8004/search",
    "bookings": "http://localhost:8005/bookings",
    "payments": "http://localhost:8006/payments",
    "notifications": "http://localhost:8007/notifications",
    "ai": "http://localhost:8008/ai",
    "roommate": "http://localhost:8012",
    "moderation": "http://localhost:8009/moderation",
    "admin": "http://localhost:8010/admin",
    "reports": "http://localhost:8011/reports",
}

DEFAULT_POLICIES = {
    "ip": {"limit_per_minute": 120, "burst_limit": 30},
    "user": {"limit_per_minute": 240, "burst_limit": 60},
}


def seed_gateway_defaults(apps, schema_editor):
    route_model = apps.get_model("gateway", "GatewayRouteRegistry")
    policy_model = apps.get_model("gateway", "GatewayRateLimitPolicy")

    for route_prefix, upstream_base_url in DEFAULT_ROUTES.items():
        route_model.objects.update_or_create(
            route_prefix=route_prefix,
            defaults={
                "upstream_base_url": upstream_base_url,
                "is_active": True,
            },
        )

    for scope, policy in DEFAULT_POLICIES.items():
        policy_model.objects.update_or_create(
            scope=scope,
            defaults={
                "limit_per_minute": policy["limit_per_minute"],
                "burst_limit": policy["burst_limit"],
                "is_active": True,
            },
        )


def unseed_gateway_defaults(apps, schema_editor):
    route_model = apps.get_model("gateway", "GatewayRouteRegistry")
    policy_model = apps.get_model("gateway", "GatewayRateLimitPolicy")
    route_model.objects.filter(route_prefix__in=DEFAULT_ROUTES.keys()).delete()
    policy_model.objects.filter(scope__in=DEFAULT_POLICIES.keys()).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_gateway_defaults, reverse_code=unseed_gateway_defaults),
    ]
