# Generated by Django 5.2 on 2026-04-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reporter_user_id", models.PositiveIntegerField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("user", "User"), ("housing", "Housing"), ("booking", "Booking")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(db_index=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("triaged", "Triaged"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "complaints",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["target_type", "target_id"], name="complaints_target__1cff59_idx"),
                    models.Index(fields=["reporter_user_id", "created_at"], name="complaints_reporte_5826a5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplaintEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_url", models.URLField(max_length=500)),
                ("file_type", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="moderation.complaint",
                    ),
                ),
            ],
            options={"db_table": "complaint_evidence", "ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="ModerationCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_admin_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        db_index=True,
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_case",
                        to="moderation.complaint",
                    ),
                ),
            ],
            options={"db_table": "moderation_cases", "ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[("warn", "Warn"), ("suspend", "Suspend"), ("reject_listing", "Reject Listing")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("user", "User"), ("housing", "Housing"), ("booking", "Booking")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(db_index=True)),
                ("created_by_admin_id", models.PositiveIntegerField(db_index=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="moderation.moderationcase",
                    ),
                ),
            ],
            options={"db_table": "moderation_actions", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="CaseComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_user_id", models.PositiveIntegerField(db_index=True)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="moderation.moderationcase",
                    ),
                ),
            ],
            options={"db_table": "case_comments", "ordering": ["created_at", "id"]},
        ),
    ]

