# Generated by Django 5.2.13 on 2026-04-21 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="complaint",
            new_name="complaints_target__d7983f_idx",
            old_name="complaints_target__1cff59_idx",
        ),
        migrations.RenameIndex(
            model_name="complaint",
            new_name="complaints_reporte_11e101_idx",
            old_name="complaints_reporte_5826a5_idx",
        ),
    ]
