# Generated by Codex on 2026-04-10

from django.db import migrations


def seed_default_roles(apps, schema_editor):
    role_model = apps.get_model("authentication", "AuthRole")
    role_model.objects.get_or_create(name="student")
    role_model.objects.get_or_create(name="admin")


def unseed_default_roles(apps, schema_editor):
    role_model = apps.get_model("authentication", "AuthRole")
    role_model.objects.filter(name__in=["student", "admin"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_roles, reverse_code=unseed_default_roles),
    ]

