# Generated by Django 5.2.13 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HousingFeatureVector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("vector_json", models.JSONField(default=list)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housing_feature_vectors",
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceVector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("vector_json", models.JSONField(default=list)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preference_vectors",
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("unit_id", models.PositiveIntegerField(db_index=True)),
                ("feedback_type", models.CharField(choices=[("like", "Like"), ("dislike", "Dislike")], max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendation_feedback",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HousingRecommendationResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("unit_id", models.PositiveIntegerField(db_index=True)),
                ("similarity_score", models.FloatField(db_index=True)),
                ("rank", models.PositiveIntegerField()),
                ("reasoning_json", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "housing_recommendation_results",
                "ordering": ["rank", "-similarity_score", "unit_id"],
                "unique_together": {("user_id", "unit_id", "generated_at")},
            },
        ),
    ]
