# Generated by Django 5.2.13 on 2026-04-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questionnaires",
                "ordering": ["-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RoommateMatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("candidate_user_id", models.PositiveIntegerField(db_index=True)),
                ("score", models.FloatField(db_index=True)),
                ("rank", models.PositiveIntegerField()),
                ("scoring_mode", models.CharField(default="cosine", max_length=16)),
                ("explanation_json", models.JSONField(blank=True, default=dict)),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "db_table": "roommate_match_results",
                "ordering": ["rank", "-score", "candidate_user_id"],
            },
        ),
        migrations.CreateModel(
            name="UserLifestyleVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("vector_json", models.JSONField(default=list)),
                ("dimensions_json", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_lifestyle_vectors",
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension_key", models.CharField(db_index=True, max_length=64)),
                ("prompt", models.CharField(max_length=300)),
                ("weight", models.FloatField(default=1.0)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="roommate.questionnaire",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("numeric_value", models.FloatField()),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="roommate.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserQuestionnaireAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="roommate.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_answers",
                        to="roommate.questionoption",
                    ),
                ),
            ],
            options={
                "db_table": "user_questionnaire_answers",
                "ordering": ["-created_at", "-id"],
                "unique_together": {("user_id", "question")},
            },
        ),
    ]
