# Generated by Django 5.2 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_user_id", models.PositiveIntegerField(db_index=True)),
                ("action_key", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(db_index=True, max_length=64)),
                ("target_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "admin_action_logs", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="AdminSavedView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_user_id", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("filters_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_saved_views",
                "ordering": ["name", "-updated_at"],
                "unique_together": {("admin_user_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_user_id", models.PositiveIntegerField(db_index=True)),
                ("target_type", models.CharField(db_index=True, max_length=64)),
                ("target_id", models.CharField(db_index=True, max_length=64)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "admin_notes", "ordering": ["-created_at", "-id"]},
        ),
    ]

