# Generated by Django 5.2 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIMetricsDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, unique=True)),
                ("recommendation_click_rate", models.FloatField(default=0.0)),
                ("match_accept_rate", models.FloatField(default=0.0)),
                ("recommendation_events", models.PositiveIntegerField(default=0)),
                ("roommate_match_events", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "ai_metrics_daily", "ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="BookingMetricsDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, unique=True)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("confirmed_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "booking_metrics_daily", "ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="KPIDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, unique=True)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_registrations", models.PositiveIntegerField(default=0)),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("gross_volume", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("pending_housing_count", models.PositiveIntegerField(default=0)),
                ("approved_housing_count", models.PositiveIntegerField(default=0)),
                ("notification_sent_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "kpi_daily", "ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="ModerationMetricsDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, unique=True)),
                ("complaints_opened", models.PositiveIntegerField(default=0)),
                ("complaints_resolved", models.PositiveIntegerField(default=0)),
                ("avg_resolution_hours", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "moderation_metrics_daily", "ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="PaymentMetricsDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, unique=True)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("refund_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "payment_metrics_daily", "ordering": ["-date"]},
        ),
    ]

